### ISSUE TITLE
Step 3 - Erreur de calcul -  setValue(self, int): argument 1 has unexpected type 'float' 

### ISSUE THREAD

**Issue by mbrasebin** [Art-Ev/ICEtool#17]
Bonjour,

comme vu lors du TP lors des rencontres QGIS, je rencontre l'erreur suvante  lors de l'étape sous Ubuntu 22.04 avec le jeu de données test (j'ai recalculé les raster buildingground et tree) :

 setValue(self, int): argument 1 has unexpected type 'float'. Vous trouverez l'erreur complète ci-dessous
 
![image](https://user-images.githubusercontent.com/10995312/224746623-682fd6bf-7812-489f-9162-c649d9406012.png)

Merci pour la mise à disposition de ce plugin et de l'attention que vous porterez à mon bug

**Comment by mbrasebin** [comment]
Les rasters de l'étape 2 ont été testés sur un PC Windows et ont pu être utilisés avec succès pour l'étape 3.

**Comment by clemlosc** [comment]
Bonjour, oui nous avons le même problème lors du lancement de l'étape 3. Il semble que c'est un problème de version trop récente d'un module Python nommé "numpy".
Il faut downgrade la version de numpy vers une version plus ancienne.

**Comment by Art-Ev** [comment]
@mbrasebin, avec la dernière maj le problème est-il toujours présent ?

**Comment by Guts** [comment]
Pour information, je viens de reproduire la même anomalie.

Voici le détail :


```log
TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/guts/.local/share/QGIS/QGIS3/profiles/GETEC/python/plugins/ICEtool/Scripts/ShadowGenerator/shadow_generator.py", line 419, in start_progress
    shadowresult = dsh.dailyshading(dsm, vegdsm, vegdsm2, scale, lon, lat, sizex, sizey, tv, UTC, usevegdem,
  File "/home/guts/.local/share/QGIS/QGIS3/profiles/GETEC/python/plugins/ICEtool/Scripts/ShadowGenerator/dailyshading.py", line 133, in dailyshading
    shadowresult = shadow.shadowingfunction_20(dsm, vegdem, vegdem2, azi[i], alt[i], scale, amaxvalue,
  File "/home/guts/.local/share/QGIS/QGIS3/profiles/GETEC/python/plugins/ICEtool/Scripts/Utilities/shadowingfunctions.py", line 155, in shadowingfunction_20
    dlg.progressBar.setValue(index)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'


Version de Python : 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Version de QGIS : 3.28.15-Firenze Firenze, 252ad49ddcb 
```

Version de numpy d'après la console Python :

```python
>>> import numpy
>>> numpy.__version__
'1.26.4'
```


En changeant :

https://github.com/Art-Ev/ICEtool/blob/c1cd438c61b6380490edbc0cd80d1630e7154c33/Scripts/Utilities/shadowingfunctions.py#L155

Pour :

```python
    while (amaxvalue >= dz) and (np.abs(dx) < sizex) and (np.abs(dy) < sizey):
        if forsvf == 0:
            dlg.progressBar.setValue(int(index))
```

Cela fonctionne. Désolé, j'ai un peu la flemme de faire un fork + PR toussa :sweat_smile:

**Comment by mbrasebin** [comment]
Je n'étais pas revenue sur l'issue, mais le passage sous Windows avait permis de le résoudre sauf aujourd'hui où  la solution de @Guts  m'a décoincé :) Merci à toi

**Comment by Guts** [comment]
Content que ça aie pu rendre service :)

**Comment by renaud24** [comment]
Bonjour,

J'utilise la nouvelle version de qgis (v.3.34.12, mais l'erreur s'est aussi produite avec la 3.28.14)
Je suis loin d'être expert de qgis, et encore moins de python, mais j'essaye de trifouiller pour apprendre.

A l'origine, j'ai eu le même message d'erreur que vous:
>2024-11-11T18:12:45     WARNING    Traceback (most recent call last):
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\ShadowGenerator\shadow_generator.py", line 419, in start_progress
              shadowresult = dsh.dailyshading(dsm, vegdsm, vegdsm2, scale, lon, lat, sizex, sizey, tv, UTC, usevegdem,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\ShadowGenerator\dailyshading.py", line 133, in dailyshading
              shadowresult = shadow.shadowingfunction_20(dsm, vegdem, vegdem2, azi[i], alt[i], scale, amaxvalue,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\Utilities\shadowingfunctions.py", line 155, in shadowingfunction_20
              dlg.progressBar.setValue(index)
             TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Du coup, j'ai essayé de remplacer dans le script ICEtool/Scripts/Utilities/shadowingfunctions.py la ligne 155 par les 3 lignes de code indiquées par @Guts 

Mais ca a empiré, j'ai fait bugger l'outil :
>2024-11-11T15:28:28     WARNING    Extension ICEtool : Cette extension est désactivée car elle a précédemment planté QGIS.
2024-11-11T15:28:40     WARNING    Erreur Python : Impossible de charger l'extension 'ICEtool' provoque une erreur lors de l'appel à sa méthode classFactory() Voir le journal des erreurs Python pour plus de détails


>2024-11-11T15:28:40     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\__init__.py", line 36, in classFactory
              from .ICEtool import ICEtoolPlugin
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\ICEtool.py", line 37, in 
              from .ICEtool_provider import ICEtoolProvider
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\ICEtool_provider.py", line 46, in 
              from .Scripts.Step3_UMEPshadows import UMEP_shadows
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\Step3_UMEPshadows.py", line 19, in 
              from .ShadowGenerator.shadow_generator import ShadowGenerator
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\ShadowGenerator\shadow_generator.py", line 39, in 
              from . import dailyshading as dsh
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\ShadowGenerator\dailyshading.py", line 4, in 
              from ..Utilities import shadowingfunctions as shadow
              File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/r_molas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\Utilities\shadowingfunctions.py", line 156
              if forsvf == 0:
             IndentationError: expected an indented block after 'while' statement on line 155
             
Je ne comprends pas où j'ai loupé le truc, ca fait 3 jours que j'essaye d'identifier le bug (même en reprenant l'exemple de l'INSA de Toulouse), et je suis tombé sur ce post... Je dois m'y prendre comme un manche (mais je ne sais pas où), et donc j'envoie une bouteille à la mer!!! 
J'ai également essayé d'utiliser l'extension originale de l'UMEP: (Solar Radiation: Shadow Generator) sans succès également...

Merci beaucoup pour votre aide...
Bonne journée, et encore merci pour cette extension !!!!

**Comment by renaud24** [comment]
Salut,
J'ai pu finalement m'en sortir en utilisant l'extension originale de l'UMEP, solar radiation : shadow generator, en indiquant à la fin un "Aggregated (or single) shadow raster" à la fin, en ne laissant pas la valeur par défaut... 
Si ca peut aider quelqu'un ;)

**Comment by mbrasebin** [comment]
J'ai créé un pull request ici reprenant la modif de gust : https://github.com/Art-Ev/ICEtool/pull/34 

Soit il faut réinstaller le plugin à partir du code du pull request soit au moins récupérer et remplacer le fichier Scripts/Utilities/shadowingfunctions.py

**Comment by ALB1FR** [comment]
> Salut, J'ai pu finalement m'en sortir en utilisant l'extension originale de l'UMEP, solar radiation : shadow generator, en indiquant à la fin un "Aggregated (or single) shadow raster" à la fin, en ne laissant pas la valeur par défaut... Si ca peut aider quelqu'un ;)

Salut, je rencontre exactement les mêmes déboires 😭 j'ai installé UMEP mais j'avoue ne pas comprendre comment l'utiliser puis la passerelle entre UMEP et QGIS pour rependre Ice tool à la bonne étape ? Si tu peux expliciter comment tu t'en es sorti stp 🙏🙏

**Comment by renaud24** [comment]
Salut,
Je m'en suis sorti en utilisant "solar radiation: shadow generator"
Où tu renseignes:
- ton raster "batiment" dans la première ligne
- ton raster "vegetation" dans la seconde
- les 5 lignes suivantes, tu laisses par défaut, jusqu'à UTC où tu mets à 1
- tu renseignes la date
- l'intervalle de temps : 60
- après tu ne coches pas "cast only one shadow", du coup tu ne modifies pas l'heure suivante
- et dans "output folder", tu sélectionnes "sauvegarder dans le répertoire" sur les trois petits points à droite, et tu pointes vers ton Step 3

Là, tu généreras tes rasters d'ombrage heure par heure (de 6h à 20h). Par contre ne soit pas étonné, ca prend du temps...
Moi comme ca, ca marche (quelqu'un valide la manip?)...  Bon courage.
